apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhealthapi-deployment
  namespace: myhealthapi
  labels:
    app: myhealthapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myhealthapi
  template:
    metadata:
      labels:
        app: myhealthapi
    spec:
      containers:
        - name: myhealthapi
          image: stephenprasadee/myhealthapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: myhealthapi-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
